const adjectives = [
  "awful",
  "boring",
  "cheap",
  "clumsy",
  "cruel",
  "dark",
  "depressing",
  "disgusting",
  "dull",
  "empty",
  "evil",
  "fragile",
  "gross",
  "harsh",
  "horrible",
  "incompetent",
  "insane",
  "irritating",
  "lazy",
  "lonely",
  "loud",
  "mean",
  "miserable",
  "mediocre",
  "noisy",
  "overpriced",
  "pathetic",
  "picky",
  "puny",
  "rude",
  "selfish",
  "shallow",
  "stupid",
  "tacky",
  "tasteless",
  "ugly",
  "unpleasant",
  "unreliable",
  "weak",
  "wrong",
  "wretched",
  "worthless",
];

const nouns = [
  "apples",
  "bananas",
  "chairs",
  "tables",
  "dogs",
  "cats",
  "trees",
  "houses",
  "books",
  "pens",
  "pencils",
  "papers",
  "scissors",
  "cups",
  "plates",
  "forks",
  "knives",
  "spoons",
  "beds",
  "windows",
  "doors",
  "walls",
  "floors",
  "ceilings",
  "keys",
  "locks",
  "lights",
  "fans",
  "doorknobs",
  "windowpanes",
  "doorframes",
  "chair legs",
  "table legs",
  "tabletops",
  "chair seats",
  "light switches",
  "fan blades",
  "keyholes",
  "lock mechanisms",
  "ceiling lights",
  "floor tiles",
  "doorknob stems",
  "window latches",
  "window sills",
  "window frames",
  "tablecloths",
  "chair cushions",
  "bedsheets",
];

//const randomAdj = document.getelementById();
//const randomNoun = document.getelementById();

const cheesyYoutubeTitle = () => {
  let i = Math.floor(Math.random() * adjectives.length);
  let j = Math.floor(Math.random() * nouns.length);
  return `The ${adjectives[i]} TRUTH about ${nouns[j]}.`;
};

console.log(cheesyYoutubeTitle())